/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'flashSale' : IDL.Null,
  'resell' : IDL.Null,
  'offer' : IDL.Null,
  'deal' : IDL.Null,
  'loot' : IDL.Null,
  'quickSale' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Int,
  'title' : IDL.Text,
  'expiryTimestamp' : IDL.Opt(IDL.Int),
  'originalPrice' : IDL.Float64,
  'dealPrice' : IDL.Float64,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : Category,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'listingId' : IDL.Text,
  'customerAddress' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Int,
});

export const idlService = IDL.Service({
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        Category,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
  'getOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [],
      [],
    ),
  'toggleListingActive' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        Category,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'flashSale' : IDL.Null,
    'resell' : IDL.Null,
    'offer' : IDL.Null,
    'deal' : IDL.Null,
    'loot' : IDL.Null,
    'quickSale' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Int,
    'title' : IDL.Text,
    'expiryTimestamp' : IDL.Opt(IDL.Int),
    'originalPrice' : IDL.Float64,
    'dealPrice' : IDL.Float64,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : Category,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'listingId' : IDL.Text,
    'customerAddress' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Int,
  });
  
  return IDL.Service({
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          Category,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
    'getOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [],
        [],
      ),
    'toggleListingActive' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          Category,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };