/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'flashSale' : null } |
  { 'resell' : null } |
  { 'offer' : null } |
  { 'deal' : null } |
  { 'loot' : null } |
  { 'quickSale' : null };
export interface Listing {
  'id' : string,
  'stockQuantity' : bigint,
  'title' : string,
  'expiryTimestamp' : [] | [bigint],
  'originalPrice' : number,
  'dealPrice' : number,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : Category,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'listingId' : string,
  'customerAddress' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null } |
  { 'processing' : null };
export interface _SERVICE {
  'createListing' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      Category,
      string,
      bigint,
      [] | [bigint],
      string,
    ],
    undefined
  >,
  'deleteListing' : ActorMethod<[string, string], undefined>,
  'getActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getListing' : ActorMethod<[string], [] | [Listing]>,
  'getOrder' : ActorMethod<[string, string], [] | [Order]>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, bigint, bigint],
    undefined
  >,
  'toggleListingActive' : ActorMethod<[string, string], undefined>,
  'updateListing' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      Category,
      string,
      bigint,
      [] | [bigint],
      string,
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];